project:
  type: website
  output-dir: docs
website:
  title: "Nicol√°s Rojo"
  navbar:
    background: "#ffffff"
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://linkedin.com/

# ... (lo de arriba igual)
format:
  html:
    theme: cosmo
    css: styles.css
    include-before-body: sc-visuals.html
    include-in-header: aos-head.html
